name: Deploy to EC2 (Build on EC2)

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
           
            echo "---- Pulling latest code ----"

            # Clone or update repo in ~/fr_model
            if [ ! -d ~/fr_model ]; then
              git clone https://github.com/uctconsulting12/fr_model.git ~/fr_model
            else
              cd ~/fr_model
              git pull origin main
            fi

            echo "---- Building Docker image ----"
            cd ~/fr_model
            sudo docker build -t fr_image .
            echo "--- remove none images ------"
            sudo docker image prune -f

            echo "---- Stopping old container ----"
            sudo docker stop fr_container || true
            sudo docker rm fr_container || true

            echo "---- Running new container with AWS creds ----"
            sudo docker run -d \
            --name fr_container \
            -p 8005:8005 \
            --gpus all \
            -v /home/ubuntu/.aws:/root/.aws \
            fr_image

            echo "Deployment completed. "
